export default [
  { value: "Acne", label: "Acne" },
  { value: "ADD/ADHD", label: "ADD/ADHD" },
  { value: "Addictions", label: "Addictions"},
  { value: "Air Pollution", label: "Air Pollution" },
  { value: "Air Purification", label: "Air Purification" },
  { value: "Alertness", label: "Alertness" },
  { value: "Allergies", label: "Allergies"},
  { value: "Allergies (skin)", label: "Allergies (skin)" },
  { value: "Antioxidant", label: "Antioxidant" },
  { value: "Anxiety", label: "Anxiety" },
  { value: "Aphrodisiac", label: "Aphrodisiac"},
  { value: "Arthritis", label: "Arthritis" },
  { value: "Back Pain", label: "Back Pain" },
  { value: "Bacterial Infection", label: "Bacterial Infection" },
  { value: "Balance", label: "Balance"},
  { value: "Bloating", label: "Bloating" },
  { value: "Blood Clots", label: "Blood Clots" },
  { value: "Bronchitis", label: "Bronchitis" },
  { value: "Bruises", label: "Bruises"},
  { value: "Bug Bites", label: "Bug Bites" },
  { value: "Burns", label: "Burns" },
  { value: "Calming", label: "Calming" },
  { value: "Carpal Tunnel", label: "Carpal Tunnel"},
  { value: "Cartilage Injury", label: "Cartilage Injury" },
  { value: "Cholesterol", label: "Cholesterol" },
  { value: "Circulation", label: "Circulation" },
  { value: "Clarity", label: "Clarity"},
  { value: "Cleansing", label: "Cleansing" },
  { value: "Cold Sores", label: "Cold Sores" },
  { value: "Colds", label: "Colds" },
  { value: "Concentration", label: "Concentration"},
  { value: "Concussion", label: "Concussion" },
  { value: "Confidence", label: "Confidence" },
  { value: "Congestion", label: "Congestion" },
  { value: "Cooking", label: "Cooking"},
  { value: "Cooling", label: "Cooling" },
  { value: "Corns", label: "Corns" },
  { value: "Cough", label: "Cough" },
  { value: "Coughs", label: "Coughs"},
  { value: "Cramps", label: "Cramps" },
  { value: "Cramps/Spasms", label: "Cramps/Spasms" },
  { value: "Creativity", label: "Creativity" },
  { value: "Dandruff", label: "Dandruff"},
  { value: "Depression", label: "Depression" },
  { value: "Dermatitis", label: "Dermatitis" },
  { value: "Dermatitis/Eczema", label: "Dermatitis/Eczema" },
  { value: "Diabetes", label: "Diabetes"},
  { value: "Diaper Rash", label: "Diaper Rash" },
  { value: "Digestion", label: "Digestion" },
  { value: "Digestive Support", label: "Digestive Support" },
  { value: "Disinfectant", label: "Disinfectant"},
  { value: "Diuretic", label: "Diuretic" },
  { value: "Dry Skin", label: "Dry Skin" },
  { value: "Earache", label: "Earache" },
  { value: "Energizing", label: "Energizing"},
  { value: "Energy", label: "Energy" },
  { value: "Fear", label: "Fear" },
  { value: "Fever", label: "Fever" },
  { value: "Flu", label: "Flu"},
  { value: "Focus", label: "Focus" },
  { value: "Grease", label: "Grease" },
  { value: "Grief/Sorrow", label: "Grief/Sorrow" },
  { value: "Guilt", label: "Guilt"},
  { value: "Gum Disease", label: "Gum Disease" },
  { value: "Gum/Grease Removal", label: "Gum/Grease Removal" },
  { value: "Hangover", label: "Hangover" },
  { value: "Happiness", label: "Happiness"},
  { value: "Headache", label: "Headache" },
  { value: "Heartburn", label: "Heartburn" },
  { value: "High Blood Pressure", label: "High Blood Pressure" },
  { value: "Hormones", label: "Hormones"},
  { value: "Hormones (balancing)", label: "Hormones (balancing)" },
  { value: "Hot Flashes", label: "Hot Flashes" },
  { value: "Indigestion", label: "Indigestion" },
  { value: "Infection", label: "Infection"},
  { value: "Inflammation", label: "Inflammation" },
  { value: "Insomnia", label: "Insomnia" },
  { value: "Itching", label: "Itching" },
  { value: "Joint Injuries", label: "Joint Injuries"},
  { value: "Joint Pain", label: "Joint Pain" },
  { value: "Joy", label: "Joy" },
  { value: "Laryngitis", label: "Laryngitis" },
  { value: "Meditation", label: "Meditation"},
  { value: "Memory", label: "Memory" },
  { value: "Menopause", label: "Menopause" },
  { value: "Menstruation", label: "Menstruation" },
  { value: "Mental Fatigue", label: "Mental Fatigue"},
  { value: "Mildew", label: "Mildew" },
  { value: "Mold", label: "Mold" },
  { value: "Morning Sickness", label: "Morning Sickness" },
  { value: "Mosquito Repellent", label: "Mosquito Repellent"},
  { value: "Muscle Aches", label: "Muscle Aches" },
  { value: "Muscle Development", label: "Muscle Development" },
  { value: "Muscle Fatigue", label: "Muscle Fatigue" },
  { value: "Muscle Fatigue/Pain", label: "Muscle Fatigue/Pain"},
  { value: "Muscle Pain", label: "Muscle Pain" },
  { value: "Nausea", label: "Nausea" },
  { value: "Nervousness", label: "Nervousness" },
  { value: "Pain", label: "Pain"},
  { value: "Parasites", label: "Parasites" },
  { value: "Passion", label: "Passion" },
  { value: "Perfume", label: "Perfume" },
  { value: "Purify", label: "Purify" },
  { value: "Purification", label: "Purification"},
  { value: "PMS", label: "PMS" },
  { value: "Poison Ivy/Oak", label: "Poison Ivy/Oak" },
  { value: "Positive Feeling", label: "Positive Feeling" },
  { value: "Rashes", label: "Rashes"},
  { value: "Relaxation", label: "Relaxation" },
  { value: "Relaxing", label: "Relaxing" },
  { value: "Release", label: "Release" },
  { value: "Repellent", label: "Repellent"},
  { value: "Respiratory Ailments", label: "Respiratory Ailments" },
  { value: "Respiratory Infection", label: "Respiratory Infection" },
  { value: "Scarring (prevention)", label: "Scarring (prevention)" },
  { value: "Scars", label: "Scars"},
  { value: "Sedative", label: "Sedative" },
  { value: "Shock", label: "Shock" },
  { value: "Sinusitis", label: "Sinusitis" },
  { value: "Skin", label: "Skin"},
  { value: "Sleep", label: "Sleep" },
  { value: "Stings", label: "Stings" },
  { value: "Stress", label: "Stress" },
  { value: "Stroke", label: "Stroke"},
  { value: "Sunscreen", label: "Sunscreen" },
  { value: "Tension", label: "Tension" },
  { value: "Termite Repellent", label: "Termite Repellent" },
  { value: "Tissue Repair", label: "Tissue Repair"},
  { value: "Toothache", label: "Toothache" },
  { value: "Uplifting", label: "Uplifting" },
  { value: "Vertigo", label: "Vertigo" },
  { value: "Viral Infection", label: "Viral Infection"},
  { value: "Warming", label: "Warming" },
  { value: "Warts", label: "Warts" },
  { value: "Weight Loss", label: "Weight Loss" },
  { value: "Whiplash", label: "Whiplash"},
  { value: "Wounds", label: "Wounds" },
  { value: "Wrinkles", label: "Wrinkles"},
  { value: "Yoga", label: "Yoga" },

];
