export default [
  "Absurdist/Surreal/whimsical",
  "Action",
  "Adventure",
  "Comedy",
  "Crime",
  "Documentary",
  "Drama",
  "Fantasy",
  "Historical",
  "Historical fiction",
  "Horror",
  "Magical realism",
  "Mystery",
  "Paranoid",
  "Philosophical",
  "Political",
  "Romance",
  "Satire",
  "Science fiction",
  "Slice of Life",
  "Thriller",
  "Western",
];
